---
title: "AdeptWork"
output: html_document
---

```{r setup, include=FALSE}
library(fs)
library(tidyverse)
library(lubridate)
library(DBI)
library(RPostgres)
library(sf)
library(ggspatial)
library(prettymapr)
library(units)
library(opmitools)
library(dplyr)

options(scipen = 999)
user_path <- path_home()
```

#Using test query to upload data into R

```{r}
adept_trip_archive <- read_csv(paste0(user_path, "/OneDrive - MBTA/Desktop/ADEPT_TRIP_ARCHIVE.csv"))
```

```{r}
adept_testing <- adept_trip_archive %>%
  filter(Status == "S") %>%
  mutate(trip_date = mdy_hms(Tripdate)) %>%
  filter(trip_date >= "2025-03-01") %>%
  filter(trip_date <= "2025-03-31")
```

```{r}
table(adept_testing$trip_date)
```

#Looking at early March days in detail for differences

```{r}
ride_early_march <- read_csv(paste0(user_path, "/OneDrive - MBTA/Documents - OPMI/01 Admin/00 Data Strategy/Ongoing Activities/Open Data Portal/Data/Raw Datasets/Ridership Data/The RIDE/RIDE_Trips_Test_5.csv"))
```

```{r}
march_testing <- ride_early_march %>%
  rename(trip_date = 'Trip Date') %>%
  rename(wc_seats = 'Wc Seats')
```

```{r}
table(march_testing$wc_seats)
```

```{r}
table(march_testing$Status)
```

