---
title: "AFC_work"
author: "Jett Knight, BI Analyst, OPMI"
output: html_document
date: "2024-11-08"
---

#Setup

```{r setup, include=FALSE}
library(fs)
library(tidyverse)
library(lubridate)
library(DBI)
library(RPostgres)
library(sf)
library(ggspatial)
library(prettymapr)
library(units)
library(opmitools)

options(scipen = 999)
```

#DB Connection

```{r}
user_sp <- "jknight2"
user <- "jknight"
user_pgadmin <- "jknight2"

sp_link <- paste0("C:/Users/",user_sp,"/OneDrive - MBTA/Documents - OPMI/02 Active Projects/2024 AFC 2.0/Public Rollout Analyses/Tableau/")

con_dmap <-
  dbConnect(
    Postgres(),
    dbname = "dmap_import",
    user = user_pgadmin,
    password = rstudioapi::askForPassword(),
    port = 5432,
    host = "dmap-import-prod.cluster-ro-cw84s0ixvuei.us-east-1.rds.amazonaws.com",
    sslmode = "require"
  )

con_rs <-
  dbConnect(
    Postgres(),
    dbname = "mbta_dw",
    user = user,
    password = rstudioapi::askForPassword(),
    port = 5432,
    host = "opmi-research-server.cluster-csb3ld1kts7u.us-east-1.rds.amazonaws.com",
    sslmode = "require"
  )
```

#Analysis 1

```{r}
recent_discrepant_taps <- dbGetQuery(con_rs, paste0("SELECT * FROM ridership.afc2_device_location_issues WHERE svc_date >= '2025-02-01'"))
```

```{r}
subway_discrepant_taps <- recent_discrepant_taps %>%
  filter(operator_name == 'Subway')
```

```{r}
correct_subway_taps <- subway_discrepant_taps %>%
  filter(over_150m == 'Lat/Lon within 150m of Displayed Stop Point')

incorrect_subway_taps <- subway_discrepant_taps %>%
  filter(over_150m == 'Lat/Lon Farther than 150m from Displayed Stop Point')

na_taps <- subway_discrepant_taps %>%
  filter(over_150m == 'BMV Trx Missing Lat/Lon')
```

```{r}
table(subway_discrepant_taps$over_150m)
```

```{r}
sort(table(na_taps$stop_name_from_stoppoint))
table(na_taps$stop_name_from_coordinates)
```

#Analysis 2

```{r}
stop_id_population <- dbGetQuery(con_dmap, paste0("SELECT transaction_dtm, external_stop_point_id FROM public.use_transaction_location WHERE transaction_dtm >= '2024-08-01'"))
```

```{r}
stop_id_population <- stop_id_population %>%
  mutate(stop_point_id_date = as.Date(transaction_dtm))

stop_point_nas <- stop_id_population %>%
  filter(is.na(external_stop_point_id))

stop_point_complete <- stop_id_population %>%
  filter(!is.na(external_stop_point_id))
```

```{r}
table(stop_point_nas$stop_point_id_date)
```

```{r}
table(stop_point_complete$stop_point_id_date)
```

```{r}
stop_point_recent <- stop_id_population %>%
  filter(stop_point_id_date >= '2025-02-01')

recent_nas <- stop_point_recent %>%
  filter(is.na(external_stop_point_id))

recent_complete <- stop_point_recent %>%
  filter(!is.na(external_stop_point_id))
```

#Analysis 3

```{r}
jan_latlon_missing <- dbGetQuery(con_rs, paste0("SELECT * FROM ridership.afc2_device_location_issues WHERE svc_date = '2025-01-21'"))
```

```{r}
subway_only <- jan_latlon_missing %>%
  filter(operator_name == 'Subway')
```

```{r}
correct_jan_taps <- subway_only %>%
  filter(over_150m == 'Lat/Lon within 150m of Displayed Stop Point')

incorrect_jan_taps <- subway_only %>%
  filter(over_150m == 'Lat/Lon Farther than 150m from Displayed Stop Point')

na_jan_taps <- subway_only %>%
  filter(over_150m == 'BMV Trx Missing Lat/Lon' | over_150m == 'BMV Trx Missing Stop Point Name')
```

```{r}
table(subway_only$over_150m)
```

```{r}
table(subway_only$ride_count)
```

```{r}
user_path <- path_home()

write.csv(subway_only, file = paste0(user_path, "/OneDrive - MBTA/Desktop/subway_discrepancies_0121.csv"), row.names = F)
```

#Analysis 4 (rewrite this as needed for Mieka asks)

```{r}
feb_discrepancies_total <- dbGetQuery(con_rs, paste0("SELECT * FROM ridership.afc2_device_location_issues WHERE svc_date BETWEEN '2025-02-01' AND '2025-02-28'"))
```

```{r}
table(feb_discrepancies_total$svc_date)
```

```{r}
user_path <- path_home()

write.csv(feb_discrepancies_total, file = paste0(user_path, "/OneDrive - MBTA/Desktop/feb_discrepancies_total.csv"), row.names = F)
```

#Analysis 5

```{r}
#Dave Barker ask about new Charlie Card data and whether or not it's showing up in production
user_path <- path_home()

charlie_card_population <- dbGetQuery(con_dmap, paste0("SELECT transaction_dtm, txn_status_name, media_class_desc, media_class_id, media_class_name, media_type_desc, media_type_id, media_type_name FROM public.use_transaction_location WHERE transaction_dtm >= '2025-02-01' AND transaction_dtm <= '2025-05-13'"))
```

```{r}
charlie_card_filtered <- charlie_card_population %>%
  mutate(svc_date = as.Date(transaction_dtm)) %>%
  filter(media_class_desc != "Bank Card") %>%
  filter(txn_status_name == "Success") %>%
  select(svc_date, txn_status_name, media_class_desc, media_class_id, media_class_name, media_type_desc, media_type_id, media_type_name)
```

```{r}
pass_purchase_population <- dbGetQuery(con_dmap, paste0("SELECT transaction_dtm, txn_status_name, device_type_name, media_class_desc, media_class_id, media_class_name, media_type_desc, media_type_id, media_type_name FROM public.sale_transaction"))
```

```{r}
pass_purchase_filtered <- pass_purchase_population %>%
  mutate(svc_date = as.Date(transaction_dtm)) %>%
  select(svc_date, txn_status_name, device_type_name, media_class_desc, media_class_id, media_class_name, media_type_desc, media_type_id, media_type_name)
```

```{r}
table(pass_purchase_filtered$device_type_name)
```
